#!/usr/bin/env bash
# A script that manages the "manage_my_process" process

if [ "$#" -ne 1 ]
then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit
fi

case "$1" in
    "start")
	bash manage_my_process &
	pgrep -f manage_my_process | tail -n 1 > my_process.pid
	sudo cp my_process.pid /var/run
	echo "manage_my_process started"
	;;
    "stop")
	sudo rm /var/run/my_process.pid
	kill $(ps auxf | grep manage_my_process | tail -n 1 | awk '{print $2}')
	echo "manage_my_process stopped"
	;;
    "restart")
	kill $(ps auxf | grep manage_my_process | tail -n 1 | awk '{print $2}')
	sudo rm /var/run/my_process.pid
	bash manage_my_process &
	pgrep -f manage_my_process | tail -n 1 > my_process.pid
	sudo cp my_process.pid /var/run
	echo "manage_my_process restarted"
	;;
    *)
	echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
